apiVersion: v1
kind: Service
metadata:
  name: nodejs-istio-routing-service
  labels:
    app: nodejs-istio-routing-service
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: nodejs-istio-routing-service
    project: nodejs-istio-routing-service
